### PR TITLE
firstTradeId comes as a lowercase f in the API

### PR DESCRIPTION
**Pull request by thiagosouza**
checkout this documentation https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#klinecandlestick-streams

### CODE REVIEW

**Comment by zoeyg** [comment]
It's a potentially breaking change that should be reserved for the next major release.

**Comment by tiagosiebler** [comment]
If you want to revisit this @thiagosouza, now is your chance in the next major release: #122

**Comment by thiagosouza** [comment]
> If you want to revisit this @thiagosouza, now is your chance in the next major release: #122

yes, I am not quite sure this commit is still relevant. I revisited the official doc and they have both `f` and `F` (lowercase and uppercase).

**Comment by tiagosiebler** [comment]
> > If you want to revisit this @thiagosouza, now is your chance in the next major release: #122
> 
> yes, I am not quite sure this commit is still relevant. I revisited the official doc and they have both `f` and `F` (lowercase and uppercase).

Just checked where the change was - 24hr ticker events. Seems it's working correctly in the beta release, I've added an example:
https://github.com/tiagosiebler/binance/blob/v2.0.0/beta/examples/ws-public.ts#L35

Comparison of raw vs formatted: 
Screenshot 2021-08-08 at 10 52 10

Kline data is also looking good once formatted. I'll close this for now, but if you have any other observations, tickets or pull requests are welcome. Thank you!

**Pull request closed without merging**
