### PR TITLE
FIXED Signature for this request is not valid

### PR DESCRIPTION
**Pull request by rxcod9**
data needs to be inside BODY rather than in URL for POST requests

jaggedsoft/php-binance-api#248
binance-exchange/php-binance-api#59
https://github.com/yasinkuyu/binance-trader/pull/263

### CODE REVIEW

**Comment by noahwalugembe** [comment]
i am getting Signature for this request is not valid. error my code just work only for a small time and the stopes. the cod blow has bean working for 4 weeks but now it gives me
{ Signature for this request is not valid. error}

PATH = '/api/v3/account'
       
   
        timestamp = int(time.time() * 1000)
        params = {
           
           'recvWindow': 5000,
           'timestamp': timestamp
        }

        query_string = urlencode(params)
        params['signature'] = hmac.new(self.SECRET_KEY.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256).hexdigest()

        url = urljoin(self.BASE_URL, PATH)
        r = requests.get(url, headers=self.headers, params=params)

**Comment by tiagosiebler** [comment]
> i am getting Signature for this request is not valid. error my code just work only for a small time and the stopes. the cod blow has bean working for 4 weeks but now it gives me
> { Signature for this request is not valid. error}

Can you try the code change from this PR? The rest of this PR is not in sync with master at the moment, so it would be easiest to try this change in your installed version of the binance module:
https://github.com/zoeyg/binance/pull/75/files

Does the issue stop happening?

@rxcod9 Hi Ramakant, can you pull the latest master into your `patch-1` branch linked to this PR?

**Comment by noahwalugembe** [comment]
am not using an sdk how can i change the code 
blow
timestamp = int(time.time() * 1000)
    params = {
       
       'recvWindow': 5000,
       'timestamp': timestamp
    }

    query_string = urlencode(params)
    params['signature'] = hmac.new(self.SECRET_KEY.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256).hexdigest()

    url = urljoin(self.BASE_URL, PATH)
    r = requests.get(url, headers=self.headers, params=params)

**Comment by tiagosiebler** [comment]
Thank you for the contribution. Fixed in #122. Please try it there and provide feedback.

**Pull request closed without merging**
