### PR TITLE
v2.9.4: update flexible savings endpoints

### PR DESCRIPTION
**Pull request by MartoMcfly**
Replaced some deprecated endpoints for updated flexible savings ones. (old endpoints returned "This endpoint has been deprecated, please remove as soon as possible."

## Summary
changed end points
## Additional Information
Replaced some deprecated endpoints for updated flexible savings ones. (old endpoints returned "This endpoint has been deprecated, please remove as soon as possible."

### CODE REVIEW

**Comment by MartoMcfly** [comment]
Done! Package JSON updated

**Review by tiagosiebler — APPROVED** [review]
Looks great, thanks!

**Comment by MartoMcfly** [comment]
As always thanks for the fast response and review! :)

**Comment by tiagosiebler** [comment]
Np, thanks for helping improve the lib :)

**Pull request merged**
