### PR TITLE
Feature: added a function that gets subAccount deposit history from s…

### PR DESCRIPTION
**Pull request by MartoMcfly**
…api/v1/broker/subAccount/depositHist

Signed-off-by: MartoMcfly <martinpelaez@hotmail.es>

## Summary
Feature: added a function that gets subAccount deposit history from sapi/v1/broker/subAccount/depositHist

## Additional Information
No breaking changes or dependencies added on this pull request

### CODE REVIEW

**Review by tiagosiebler — APPROVED** [review]
Thanks

**Comment by Xavier59** [comment]
Response type different than the one described in api documentation. Which one is correct ?

https://binance-docs.github.io/Brokerage-API/Brokerage_Operation_Endpoints/#get-sub-account-deposit-history

@MartoMcfly

**Comment by Xavier59** [comment]
Can confirm typing were incorrect. Correct typings:

```typescript
  getBrokerSubAccountDepositHistory(
    params?: GetBrokerSubAccountDepositHistoryParams
  ): Promise<BrokerSubAccountDepositHistory[]> {
    return this.getPrivate('sapi/v1/broker/subAccount/depositHist', params);
  }
```

```typescript
export interface BrokerSubAccountDepositHistory {
    depositId: string,
    subAccountId: string,
    amount: string,
    coin: string,
    network: string,
    status: number,
    address: string,
    addressTag: string,
    txId: string,
    insertTime: number,
    sourceAddress: string,
    confirmTimes: string
}
```

@tiagosiebler @MartoMcfly

**Comment by tiagosiebler** [comment]
> 

Hey @Xavier59 almost missed this - silly question at a glance, does this mean that the typing in this SDK needs an update for that interface?

**Comment by Xavier59** [comment]
Yes @tiagosiebler , this interface need an update with the model I gave above :)

**Comment by tiagosiebler** [comment]
> Yes @tiagosiebler , this interface need an update with the model I gave above :)

Thanks @Xavier59 - fixed via #328 in v3.6.0. Should be on npm shortly. In future, if you comment somewhere like here and I potentially missed it, please feel free to open a new issue. I read your comments a while back but then totally forgot about it since it was hidden away in this thread. Thanks for sharing the corrected type too!

**Pull request merged**
